apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xhires-ambulance-ufe-content
spec:
  microFrontend: xhires-ambulance-ufe
  element: xhires-ambulance-wl-app
  attributes:
  - name: base-path
    value: ./xhires-ambulance-wl/
  - name: api-base
    value: /xhires-api
  - name: ambulance-id
    value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xhires-ambulance-wl(/.*)?$"